version: '3'

volumes:
  db:
    driver: local
  mysql-db:
    driver: local
  management-public:
    driver: local
  configvolume:
    external: true

services:
  db-postgres:
    image: 'advantageonlineshopping/aob-postgresql-db:latest'
    container_name: aob-db-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  config:
    image: 'advantageonlineshopping/aob-config-service:latest'
    container_name: aob-config
    environment:
      - CONFIG_REPO_URI=/root/config
      - CONFIG_REPO_FILE_SYSTEM=file:///configservice/microservices
      # - CONFIG_SERVICE_ACTIVE_PROFILE=native
    ports:
      - '8888:8888'
    volumes:
      - configvolume:/root/config
    depends_on:
      - db-postgres

  discovery:
    image: 'advantageonlineshopping/aob-eureka-service:latest'
    container_name: aob-discovery
    ports:
      - '8761:8761'
    depends_on:
      - config

  gateway:
    image: 'advantageonlineshopping/aob-gateway-service:latest'
    container_name: aob-gateway
    depends_on:
      - discovery
    ports:
      - '8080:8080'
      - '443:443'
    volumes:
      - ./:/etc/certificates
    environment:
      - KEYSTORE=/etc/certificates/keystore.p12
      - KEYSTORE_ALIAS=advantagebank
      - KEYSTORE_PASSWORD=123456

  user-service:
    image: 'advantageonlineshopping/aob-user-service:latest'
    container_name: aob-user-service
    depends_on:
      - discovery
    environment:
      GATEWAY_URL: http://gateway:8080/api

  bank-account-service:
    image: 'advantageonlineshopping/aob-bank-account-service:latest'
    container_name: aob-bank-account-service
    depends_on:
      - discovery
    environment:
      GATEWAY_URL: http://gateway:8080/api

  bank-card-service:
    image: 'advantageonlineshopping/aob-bank-cards-service:latest'
    container_name: aob-bank-cards-service
    depends_on:
      - discovery

  # forecast-service:
  #   image: 'advantageonlineshopping/aob-forecast-service:latest'
  #   container_name: aob-forecast-service
  #   depends_on:
  #     - discovery

  # loan-calc-service:
  #   image: 'advantageonlineshopping/aob-loan-calc-service:latest'
  #   container_name: aob-loan-calc-service
  #   ports:
  #     - '34568-34570:34568-34570'
  #     - '23:34571'
  #   depends_on:
  #     - discovery

  webapp:
    build: ./web-app
    container_name: aob-web-app
    expose:
      - '80'
    ports:
      - 8082:80

  mysql:
    image: advantageonlineshopping/aob-mysql-db:latest
    container_name: aob-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - mysql-db:/var/lib/mysql
      - mysql-db:/var/log/mysql
    expose:
      - '3306'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass

  currency-service-api:
    image: advantageonlineshopping/aob-currencies-service
    container_name: aob-currency-service-api
    depends_on:
      - mysql
    expose:
      - '3000'
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DBHOST: mysql
      DBPORT: 3306
      DBUSER: root
      DBPASSWORD: pass
      DBDATABASE: currency
      DAILY_RATES_ENDPOINT: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
      NINETY_DAYS_RATES_ENDPOINT: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml
      FULL_HISTORY_RATES_ENDPOINT: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml

  management-console-api:
    image: advantageonlineshopping/aob-management-console-api
    container_name: aob-management-console-api
    expose:
      - '3001'
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      DBHOST: mysql
      DBPORT: 3306
      DBUSER: root
      DBPASSWORD: pass
      DBDATABASE: management
      API_URL: http://staging.advantageonlinebanking.com:8080/api/management
      DAILY_RATES_ENDPOINT: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
      NINETY_DAYS_RATES_ENDPOINT: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml
      FULL_HISTORY_RATES_ENDPOINT: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml
    volumes:
      - 'management-public:/app/dist/src/public'

  management-console-app:
    build: ./management-console-app
    container_name: aob-management-console-app
    expose:
      - '80'
    ports:
      - 8081:80

  stocks-trading-service:
    image: advantageonlineshopping/aob-stocks-trading-service
    container_name: aob-stocks-trading-service
    expose:
      - '3002'
    ports:
      - 3002:3002
    environment:
      PORT: 3002

networks:
  default:
    external:
      name: advbank
