apiVersion: v1
kind: Service
metadata:
  labels:
    advantageonlinebanking: aob-config
  name: aob-config
spec:
  type: NodePort
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    advantageonlinebanking: aob-config
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    advantageonlinebanking: aob-config
  name: aob-config
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      advantageonlinebanking: aob-config
  template:
    metadata:
      creationTimestamp: null
      labels:
        advantageonlinebanking: aob-config
    spec:
      volumes:
        - name: aob-config-volume
          configMap:
            name: aob-configmap
      containers:
        - env:
            - name: ACCOUNT_PG_HOST
              valueFrom:
                configMapKeyRef:
                  key: ACCOUNT_PG_HOST
                  name: aob-configmap
            - name: ACCOUNT_PG_PORT
              valueFrom:
                configMapKeyRef:
                  key: ACCOUNT_PG_PORT
                  name: aob-configmap
            - name: CARD_PG_HOST
              valueFrom:
                configMapKeyRef:
                  key: CARD_PG_HOST
                  name: aob-configmap
            - name: CARD_PG_PORT
              valueFrom:
                configMapKeyRef:
                  key: CARD_PG_PORT
                  name: aob-configmap
            - name: USER_PG_HOST
              valueFrom:
                configMapKeyRef:
                  key: USER_PG_HOST
                  name: aob-configmap
            - name: MANAGEMENT_CONSOLE_API_HOST
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_CONSOLE_API_HOST
                  name: aob-configmap
            - name: MANAGEMENT_CONSOLE_API_PORT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_CONSOLE_API_PORT
                  name: aob-configmap
            - name: CURRENCY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: CURRENCY_SERVICE_HOST
                  name: aob-configmap
            - name: CURRENCY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: CURRENCY_SERVICE_PORT
                  name: aob-configmap
            - name: USER_PG_PORT
              valueFrom:
                configMapKeyRef:
                  key: USER_PG_PORT
                  name: aob-configmap
            - name: CONFIG_REPO_FILE_SYSTEM
              valueFrom:
                configMapKeyRef:
                  key: CONFIG_REPO_FILE_SYSTEM
                  name: aob-configmap
            - name: CONFIG_REPO_URI
              valueFrom:
                configMapKeyRef:
                  key: CONFIG_REPO_URI
                  name: aob-configmap
            - name: CONFIG_SERVICE_ACTIVE_PROFILE
              valueFrom:
                configMapKeyRef:
                  key: CONFIG_SERVICE_ACTIVE_PROFILE
                  name: aob-configmap
            - name: SECURE_GATEWAY
              valueFrom:
                configMapKeyRef:
                  key: SECURE_GATEWAY
                  name: aob-configmap
            - name: POPULATE_JAVA_SVC_DB
              valueFrom:
                configMapKeyRef:
                  key: POPULATE_JAVA_SVC_DB
                  name: aob-configmap
          image: advantageonlineshopping/aob-config-service:latest
          name: aob-config
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

status: {}
