apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: db-postgres
  name: db-postgres
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      nodePort: 30543
  selector:
    advantageonlinebanking: db-postgres
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: db-postgres
  name: db-postgres
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      advantageonlinebanking: db-postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        advantageonlinebanking: db-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: advantageonlineshopping/aob-postgresql-db:latest
          name: aob-db-postgres
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: mysql
  name: mysql
spec:
  type: NodePort
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    advantageonlinebanking: mysql
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      advantageonlinebanking: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        advantageonlinebanking: mysql
    spec:
      containers:
        - args:
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pass
          image: advantageonlineshopping/aob-mysql-db:latest
          name: aob-mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-lib-db
            - mountPath: /var/log/mysql
              name: mysql-log-db
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: mysql-lib-db
          emptyDir: {}
        - name: mysql-log-db
          emptyDir: {}
status: {}
