apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: aob-discovery
  name: aob-discovery
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8761
      targetPort: 8761
      nodePort: 30761
  selector:
    advantageonlinebanking: aob-discovery
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: aob-discovery
  name: aob-discovery
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      advantageonlinebanking: aob-discovery
  template:
    metadata:
      creationTimestamp: null
      labels:
        advantageonlinebanking: aob-discovery
    spec:
      containers:
        - image: advantageonlineshopping/aob-eureka-service:latest
          name: discovery
          ports:
            - containerPort: 8761
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
