apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk1-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mr/zk
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: aob-gateway
  name: aob-gateway
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    advantageonlinebanking: aob-gateway
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    advantageonlinebanking: gateway-claim0
  name: gateway-claim0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: aob-gateway
  name: aob-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      advantageonlinebanking: aob-gateway
  template:
    metadata:
      creationTimestamp: null
      labels:
        advantageonlinebanking: aob-gateway
    spec:
      containers:
        - env:
            - name: KEYSTORE
              value: /etc/certificates/keystore.p12
            - name: KEYSTORE_ALIAS
              value: advantagebank
            - name: KEYSTORE_PASSWORD
              value: password
          image: advantageonlineshopping/aob-gateway-service:latest
          name: aob-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /etc/certificates
              name: gateway-claim0
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: gateway-claim0
          persistentVolumeClaim:
            claimName: gateway-claim0
status: {}
