apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: management-console-api
  name: management-console-api
spec:
  type: NodePort
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
      nodePort: 30001
  selector:
    advantageonlinebanking: management-console-api
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: management-console-api
  name: management-console-api
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      advantageonlinebanking: management-console-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        advantageonlinebanking: management-console-api
    spec:
      containers:
        - env:
            - name: API_URL
              value: http://aob-gateway:8080/api/management
            - name: PORT
              value: "3001"
            - name: DBHOST
              value: mysql
            - name: DBPASSWORD
              value: pass
            - name: DBPORT
              value: "3306"
            - name: DBDATABASE
              value: management
            - name: DBUSER
              value: root
            - name: EUREKA_HOST
              value: aob-discovery
            - name: EUREKA_PORT
              value: "8761"
            - name: MANAGEMENT_CONSOLE_URL
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_CONSOLE_URL
                  name: aob-configmap
          image: advantageonlineshopping/aob-management-console-api:latest
          name: aob-management-console-api
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - mountPath: /app/dist/src/public
              name: management-public
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: management-public
          emptyDir: {}
status: {}
