apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: stocks-trading-service
  name: stocks-trading-service
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    advantageonlinebanking: stocks-trading-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: stocks-trading-service
  name: stocks-trading-service
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      advantageonlinebanking: stocks-trading-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        advantageonlinebanking: stocks-trading-service
    spec:
      containers:
        - env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: STOCKS_API_PORT
                  name: aob-configmap
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_HOST
                  name: aob-configmap
            - name: GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  key: GATEWAY_URL
                  name: aob-configmap
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: aob-configmap
            - name: TYPEORM_CONNECTION
              value: postgres
            - name: TYPEORM_HOST
              value: db-postgres
            - name: TYPEORM_DATABASE
              value: stocks_trading_service
            - name: TYPEORM_USERNAME
              value: postgres
            - name: TYPEORM_PASSWORD
              value: postgres
            - name: TYPEORM_PORT
              value: "5432"
            - name: TYPEORM_LOGGING
              value: "true"
            - name: TYPEORM_SYNCHRONIZE
              value: "true"
            - name: TYPEORM_ENTITIES
              value: ./dist/src/modules/**/*.entity.js
            - name: TYPEORM_MIGRATIONS
              value: ./dist/migrations/*.js
            - name: HTTP_PROXY
              value: ""
            - name: HTTPS_PROXY
              value: ""
            - name: NO_PROXY
              value: ""
          image: advantageonlineshopping/aob-stocks-trading-service:latest
          name: aob-stocks-trading-service
          ports:
            - containerPort: 3002
          imagePullPolicy: Always
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}

