apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: user-service
  name: user-service
spec:
  clusterIP: None
  ports:
    - name: headless
      port: 55555
      targetPort: 0
  selector:
    advantageonlinebanking: user-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    advantageonlinebanking: user-service
  name: user-service
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      advantageonlinebanking: user-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        advantageonlinebanking: user-service
    spec:
      containers:
        - env:
            - name: GATEWAY_URL
              value: http://aob-gateway:8080/api
          image: advantageonlineshopping/aob-user-service:latest
          name: aob-user-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

status: {}
