version: '3'

volumes:
  db:
    driver: local
  mysql-db:
    driver: local
  management-public:
    driver: local

services:
  db-postgres:
    image: 'advantageonlineshopping/aob-postgresql-db:latest'
    container_name: aob-db-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  aob-config:
    image: 'advantageonlineshopping/aob-config-service:latest'
    container_name: aob-config
    env_file:
      - .env
    ports:
      - '8888:8888'
    depends_on:
      - db-postgres

  aob-discovery:
    image: 'advantageonlineshopping/aob-eureka-service:latest'
    container_name: aob-discovery
    ports:
      - '8761:8761'
    depends_on:
      - aob-config

  aob-gateway:
    image: 'advantageonlineshopping/aob-gateway-service:latest'
    container_name: aob-gateway
    depends_on:
      - aob-discovery
    ports:
      - '8080:8080'
      - '443:443'
    volumes:
      - /etc/letsencrypt/ci.advantageonlinebanking.com:/etc/certificates
    env_file:
      - .env
  user-service:
    image: 'advantageonlineshopping/aob-user-service:latest'
    container_name: aob-user-service
    depends_on:
      - aob-discovery
    env_file:
      - .env

  bank-account-service:
    image: 'advantageonlineshopping/aob-bank-account-service:latest'
    container_name: aob-bank-account-service
    depends_on:
      - aob-discovery
    env_file:
      - .env

  bank-card-service:
    image: 'advantageonlineshopping/aob-bank-cards-service:latest'
    container_name: aob-bank-cards-service
    depends_on:
      - aob-discovery
    env_file:
      - .env

  forecast-service:
    image: 'advantageonlineshopping/aob-forecast-service:latest'
    container_name: aob-forecast-service
    depends_on:
      - aob-discovery
    env_file:
       - .env

  # loan-calc-service:
  #   image: 'advantageonlineshopping/aob-loan-calc-service:latest'
  #   container_name: aob-loan-calc-service
  #   ports:
  #     - '34568-34570:34568-34570'
  #     - '23:34571'
  #   depends_on:
  #     - discovery

  webapp:
    image: 'advantageonlineshopping/aob-web-app:latest'
    container_name: aob-web-app
    env_file:
      - .env
    expose:
      - '80'
    ports:
      - 8082:80

  mysql:
    image: advantageonlineshopping/aob-mysql-db:latest
    container_name: aob-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - mysql-db:/var/lib/mysql
      - mysql-db:/var/log/mysql
    expose:
      - '3306'
    ports:
      - 3306:3306
    env_file:
      - .env
  currency-service-api:
    image: advantageonlineshopping/aob-currencies-service:latest
    container_name: aob-currency-service-api
    depends_on:
      - mysql
    expose:
      - '3000'
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      DBDATABASE: currency
      PORT: 3000

  management-console-api:
    image: advantageonlineshopping/aob-management-console-api:latest
    container_name: aob-management-console-api
    depends_on:
      - mysql
    expose:
      - '3001'
    ports:
      - 3001:3001
    environment:
      DBDATABASE: management
      PORT: 3001
    env_file:
      - .env
    volumes:
      - 'management-public:/app/dist/src/public'

  management-console-app:
    image: advantageonlineshopping/aob-management-console-app:latest
    container_name: aob-management-console-app
    expose:
      - '80'
    ports:
      - 8081:80
    env_file:
      - .env
  stocks-trading-service:
    image: advantageonlineshopping/aob-stocks-trading-service:latest
    container_name: aob-stocks-trading-service
    expose:
      - '3002'
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db-postgres
      TYPEORM_DATABASE: stocks_trading_service
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_PORT: 5432
      TYPEORM_LOGGING: "true"
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_ENTITIES: ./dist/src/modules/**/*.entity.js
      TYPEORM_MIGRATIONS: ./dist/migrations/*.js
      HTTP_PROXY: http://proxy.mfdemoportal.com:443
      HTTPS_PROXY: http://proxy.mfdemoportal.com:443
      NO_PROXY: '*db-postgres*,aob-discovery:8761,localhost,127.0.0.1,ci.advantageonlinebanking.com'

    env_file:
      - .env

networks:
  default:
    external:
      name: advbank
